src/app/Tenderize/Models/ViewModel/MetaTagFilterViewModel.cs
using System;
using System.Collections.Generic;

namespace Tenderize.Models.ViewModel
{
    public class MetaTagFilterViewModel
    {
        public IDictionary<int, Tuple<string, bool>> MetaTags { get; set; }
    }
}

src/app/Tenderize/Controllers/TagController.cs
#region using

using System;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using Tenderize.Framework.Solr;
using Tenderize.Models;

#endregion

namespace Tenderize.Controllers
{
    [Authorize]
    public class TagController : Controller
    {
        private static readonly TenderizeDbContext Db = new TenderizeDbContext();

        public ActionResult Delete(int id)
        {
            var tag = Db.Tags.Single(a => a.Id == id);
            var questions = tag.Questions; //.ToList(); //is tolist required to process the removals? seems ineffecient
            foreach (var question in questions)
                question.Tags.Remove(tag);
            var answers = tag.Answers;
            foreach (var answer in answers)
                answer.Tags.Remove(tag);
            Db.Tags.Remove(Db.Tags.Single(a => a.Id == id));
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Improve(int? id)
        {
            if (!id.HasValue)
                return RedirectToAction("Index");
            var model = Db.Tags.FirstOrDefault(a => a.Id == id);
            if (model == null)
                return RedirectToAction("Index");
            ViewBag.Results = SolrUtil.Find(model.Text);
            return base.View(model);
        }

        public ActionResult Index()
        {
            return View(Db.Tags);
        }

        public void RunPopularityUpdate()
        {
            var tags = Db.Tags;
            foreach (var tag in tags)
            {
                var count = 0;
                try
                {
                    count = SolrUtil.Find(tag.Text).Count;
                }
                catch (Exception)
                {
                }
                tag.Popularity = count;
            }
            Db.SaveChanges();
        }

        public PartialViewResult ToggleBoost(int? id, int? tagId)
        {
            throw new NotImplementedException();
            //var currentEntity = Db.Answers.FirstOrDefault(a => a.Id == id);
            //var entity = Db.Tags.FirstOrDefault(a => a.Id == tagId);
            //if (currentEntity.Tags.Contains(entity))
            //    currentEntity.Tags.Remove(entity);
            //else
            //    currentEntity.Tags.Add(entity);
            //Db.Entry(currentEntity).CurrentValues.SetValues(currentEntity);
            //Db.SaveChanges();
            //var instance = SolrUtil.GetSolrInstance<IRelational>();
            //instance.Add(currentEntity);
            //instance.Commit();
            //ViewBag.Tag = entity;
            //return PartialView("_QuestionAnswer", currentEntity.Questions.FirstOrDefault());
        }

        public ActionResult UpdatePopularity()
        {
            new Thread(RunPopularityUpdate).Start();
            return RedirectToAction("Index");
        }
    }
}

src/app/Tenderize/Views/Shared/_Layout.cshtml
@using Tenderize.Framework.Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img src="~/Content/Images/sitecore-icon.png" height="20" alt="logo"/>
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                @if (User.IsInRole(Strings.AdminRole) || User.IsInRole(Strings.ContributorRole))
                {
                    <li>@Html.ActionLink("Tenderize", "Index", "Tenderize")</li>
                }
                <li>@Html.ActionLink("Search", "Index", "Search")</li>
                <li>@Html.ActionLink("Tags", "Index", "Tag")</li>
                @if (User.IsInRole(Strings.AdminRole))
                {
                    <li>@Html.ActionLink("Users", "Index", "User")</li>
                }
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@</ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
@*@Html.Action("_MetaTagFilter", "Home")*@
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>Tenderize 3.1</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/app")
@RenderSection("scripts", false)
</body>
</html>

src/app/Tenderize/Views/Shared/_MetaTagFilter.cshtml
@model Tenderize.Models.ViewModel.MetaTagFilterViewModel
<nav>
    <ul class="list-unstyled main-menu">

        <!--Include your navigation here-->
        <li class="text-right">
            <a href="#" id="nav-close">X</a>
        </li>
        @foreach (var mTag in Model.MetaTags)
        {
            <li>
                @Html.Label(mTag.Value.Item1)
                <input type="checkbox" value="mTag_@(mTag.Key)" @(mTag.Value.Item2 ? "checked" : "")/>
            </li>
        }


        <li>
            <a href="#">Group Example</a>
            <ul class="list-unstyled">
                <li class="sub-nav">
                    <a href="#">Sub Menu One <span class="icon"></span></a>
                </li>
                <li class="sub-nav">
                    <a href="#">Sub Menu Two <span class="icon"></span></a>
                </li>
                <li class="sub-nav">
                    <a href="#">Sub Menu Three <span class="icon"></span></a>
                </li>
                <li class="sub-nav">
                    <a href="#">Sub Menu Four <span class="icon"></span></a>
                </li>
                <li class="sub-nav">
                    <a href="#">Sub Menu Five <span class="icon"></span></a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">Menu Four <span class="icon"></span></a>
        </li>
        <li>
            <a href="#">Menu Five <span class="icon"></span></a>
        </li>
    </ul>
</nav>

<div class="navbar navbar-inverse navbar-fixed-top">

    <!--Include your brand here-->
    <a class="navbar-brand" href="#">Off Canvas Menu</a>
    <div class="navbar-header pull-right">
        <a id="nav-expander" class="nav-expander fixed">
            MENU &nbsp;<i class="fa fa-bars fa-lg white"></i>
        </a>
    </div>
</div>