src/app/Tenderize/Models/Partials/Tender.cs
using System;
using System.Linq;

namespace Tenderize.Models
{
    public partial class Tender: IEntity
    {
        
        public TenderQuestion FirstUnanswered
        {
            get
            {
                return TenderQuestions.Where(t => t.Answer == null).OrderBy(t => t.TenderSequence).FirstOrDefault() ??
                         TenderQuestions.OrderBy(t => t.TenderSequence).FirstOrDefault();

            }
        }

        public int UnansweredQuestionsCount
        {
            get { return TenderQuestions.Count(t => t.QuestionAnswer.Answer == null); }
        }

        public TimeSpan TimeRemaining
        {
            get { return new TimeSpan(0, 0, 0, UnansweredQuestionsCount * 200); }
        }

    }
}

src/app/Tenderize/Models/Partials/TenderQuestion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tenderize.Models
{
    public partial class TenderQuestion
    {
        public int NextTenderQuestion()
        {
            var list = new LinkedList<TenderQuestion>(Tender.TenderQuestions.OrderBy(q => q.TenderSequence));
            var node = list.Find(this);
            if (node == null) return 0;
            var next = node.Next;
            return next == null ? 0 : next.Value.Id;
        }

        public bool HasAnswer
        {
            get { return Answer != null; }
        }

        public int PreviousTenderQuestion()
        {
            var list = new LinkedList<TenderQuestion>(Tender.TenderQuestions.OrderBy(q => q.TenderSequence));
            var node = list.Find(this);
            if (node == null) return 0;
            var previous = node.Previous;
            return previous == null ? 0 : previous.Value.Id;
        }

        public TenderQuestion NextUnanswered
        {
            get
            {
                var nextUnansweredQuestions = Tender.TenderQuestions.OrderBy(q => q.TenderSequence)
                    .Where(question => question.TenderSequence > TenderSequence && question.QuestionAnswer.Answer == null);
                return nextUnansweredQuestions.FirstOrDefault() ?? this;
            }
        }

        public Question Question
        {
            get { return QuestionAnswer.Question; }
        }

        public Answer Answer
        {
            get { return QuestionAnswer.Answer; }
        }

    }
}

src/app/Tenderize/Models/QuestionAnswer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenderize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        public QuestionAnswer()
        {
            this.TenderQuestions = new HashSet<TenderQuestion>();
        }
    
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> AnswerId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual ICollection<TenderQuestion> TenderQuestions { get; set; }
    }
}

src/app/Tenderize/Models/Tender.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenderize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender
    {
        public Tender()
        {
            this.TenderQuestions = new HashSet<TenderQuestion>();
            this.MetaTags = new HashSet<MetaTag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> OldId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> VersionId { get; set; }
    
        public virtual ICollection<TenderQuestion> TenderQuestions { get; set; }
        public virtual Version Version { get; set; }
        public virtual ICollection<MetaTag> MetaTags { get; set; }
    }
}

src/app/Tenderize/Models/TenderQuestion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenderize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderQuestion
    {
        public int Id { get; set; }
        public int QuestionAnswerId { get; set; }
        public int TenderId { get; set; }
        public int TenderSequence { get; set; }
        public string ExcelQuestionLocation { get; set; }
        public string ExcelAnswerLocation { get; set; }
    
        public virtual QuestionAnswer QuestionAnswer { get; set; }
        public virtual Tender Tender { get; set; }
    }
}

src/app/Tenderize/Models/Tenderize.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

src/app/Tenderize/Controllers/SolrController.cs
using System.Web.Mvc;
using Tenderize.Framework.Helpers;

namespace Tenderize.Controllers
{
    [Authorize]
    public class SolrController : Controller
    {
        public PartialViewResult Progress()
        {
            if (!IndexUtil.Indexing)
            {
                return PartialView("Complete");
            }
            ViewBag.Progress = IndexUtil.GetProgress();
            return PartialView("Progress");
        }
    }
}

src/app/Tenderize/Controllers/TenderizeController.cs
#region using

using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using OfficeOpenXml;
using Tenderize.Framework.Attributes;
using Tenderize.Framework.Helpers;
using Tenderize.Framework.Solr;
using Tenderize.Models;
using Tenderize.Models.ViewModel;

#endregion

namespace Tenderize.Controllers
{
    [Authorize(Roles = "admin, contributor")]
    public class TenderizeController : Controller
    {
        private static readonly TenderizeDbContext Db = new TenderizeDbContext();

        public ActionResult Index()
        {
            var tenders = Db.Tenders.OrderByDescending(t => t.Date);
            return View(tenders);
        }

        private static string ConvertSymbols(string importString)
        {
            return importString.Replace("@@@@", Environment.NewLine).Trim();
        }

        [HttpPost]
        public ActionResult Create(string name)
        {
            var entity = new Tender
            {
                Name = name,
                Date = DateTime.Now
            };
            Db.Tenders.Add(entity);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Db.Tenders.Remove(Db.Tenders.Single(a => a.Id == id));
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Add(string answerText, int id, int nextQuestionId, string submit, int? hdnAnswerId)
        {
            var tenderQuestion = Db.TenderQuestions.Single(q => q.Id == id);
            answerText = answerText.Trim();

            if (!string.IsNullOrWhiteSpace(answerText))
            {
                if (!hdnAnswerId.HasValue)
                {
                    if (tenderQuestion.Answer != null)
                    {
                        //update
                        tenderQuestion.Answer.Text = answerText;
                    }
                    else
                    {
                        //insert
                        tenderQuestion.QuestionAnswer.Answer = new Answer {Text = answerText};
                    }
                }

                else
                {
                    var existingAnswer = Db.Answers.SingleOrDefault(a => a.Id == hdnAnswerId.Value);
                    if (existingAnswer == null)
                    {
                        tenderQuestion.QuestionAnswer.Answer = new Answer {Text = answerText};
                    }
                    else
                    {
                        if (existingAnswer == tenderQuestion.Answer)
                        {
                            //answer used == tender answer already set - weird scenario
                            if (tenderQuestion.Answer.Text.Trim() == answerText)
                            {
                                //nothing to do
                            }
                            else
                            {
                                //answer selected but text has changed - default to new answer
                                tenderQuestion.QuestionAnswer.Answer = new Answer {Text = answerText};
                            }
                        }
                        else
                        {
                            //answer used != tender answer already set
                            if (existingAnswer.Text.Trim() == answerText)
                            {
                                //existing answer used and no changes made - update reference to existing answer
                                tenderQuestion.QuestionAnswer.Answer = existingAnswer;
                            }
                            else
                            {
                                //existing answer used but changes were made - default to new answer
                                //todo: consider versioning answers
                                tenderQuestion.QuestionAnswer.Answer = new Answer {Text = answerText};
                            }
                        }
                    }
                }
            }
            else
            {
                //empty answertext
                if (tenderQuestion.Answer != null)
                {
                    tenderQuestion.QuestionAnswer.Answer = null;
                    //todo: consider deleting answer if only used for this tender
                    //scenario: placeholder answer set and then cleared
                }
            }

            Db.SaveChanges();

            if (submit == "next")
            {
                return RedirectToAction("Process", new
                {
                    id = nextQuestionId.ToString()
                });
            }
            return RedirectToAction("Process", new
            {
                id
            });
        }

        public ActionResult DeleteTag(int tagid, int questionid)
        {
            var question = Db.Questions.Single(q => q.Id == questionid);
            question.Tags.Remove(Db.Tags.Single(a => a.Id == tagid));
            Db.SaveChanges();
            return RedirectToAction("Process", new
            {
                id = question.Id.ToString()
            });
        }

        public ActionResult Export(int id)
        {
            var model = Db.Tenders.Single(a => a.Id == id);
            var info = new FileInfo(Path.Combine(Server.MapPath("~/App_Data/uploads"), "export_" + model.Id + ".xlsx"));
            if (!info.Exists)
                return View("Import", model);
            var destFileName = Path.Combine(Server.MapPath("~/App_Data/uploads"), "final_" + model.Id + ".xlsx");
            info.CopyTo(destFileName, true);
            var newFile = new FileInfo(destFileName);
            using (var package = new ExcelPackage(newFile))
            {
                foreach (var tenderQuestion in model.TenderQuestions)
                {
                    var answer = tenderQuestion.Answer;
                    if (answer == null) continue;
                    int num;
                    int num2;
                    int num3;
                    if (string.IsNullOrEmpty(tenderQuestion.ExcelAnswerLocation))
                    {
                        var strArray = tenderQuestion.ExcelQuestionLocation.Split('-');
                        num = int.Parse(strArray[0]);
                        num2 = int.Parse(strArray[1]);
                        num3 = int.Parse(strArray[2]) + 1;
                    }
                    else
                    {
                        var strArray2 = tenderQuestion.ExcelAnswerLocation.Split('-');
                        num = int.Parse(strArray2[0]);
                        num2 = int.Parse(strArray2[1]);
                        num3 = int.Parse(strArray2[2]);
                    }
                    package.Workbook.Worksheets[num].Cells[num2, num3].Value = answer.Text;
                }
                package.Save();
            }
            return File(destFileName, "APPLICATION/OCTET-STREAM", model.Name + ".xlsx");
        }

        public async Task<ActionResult> Import(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var tender = await Db.Tenders.FindAsync(id);
            if (tender == null)
            {
                return HttpNotFound();
            }

            var viewModel = new EditTenderViewModel(tender, Db);


            ViewBag.ImportFileExists =
                System.IO.File.Exists(Path.Combine(Server.MapPath("~/App_Data/uploads"), "import_" + id + ".xlsx"));
            ViewBag.ExportFileExists =
                System.IO.File.Exists(Path.Combine(Server.MapPath("~/App_Data/uploads"), "export_" + id + ".xlsx"));
            return View(viewModel);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Save")]
        public async Task<ActionResult> Save(EditTenderViewModel tender)
        {
            if (!ModelState.IsValid) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var metaTags = await ExtractTags(Request);

            var dbTender = await Db.Tenders.FindAsync(tender.Id);
            dbTender.MetaTags.Clear();

            foreach (var metaTag in metaTags)
            {
                dbTender.MetaTags.Add(metaTag);
            }
            await Db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [MultipleButton(Name="action", Argument = "Import")]
        public async Task<ActionResult> Import(Tender tender)
        {
            if (!ModelState.IsValid) return RedirectToAction("Index");
            
            var newFile =
                new FileInfo(Path.Combine(Server.MapPath("~/App_Data/uploads"), "import_" + tender.Id + ".xlsx"));
            if (!newFile.Exists)
                return View("Import", tender);

            var metaTags = await ExtractTags(Request);

            foreach (var metaTag in metaTags)
            {
                tender.MetaTags.Add(metaTag);
            }
            using (var package = new ExcelPackage(newFile))
            {
                var num = 0;
                foreach (var worksheet in package.Workbook.Worksheets)
                {
                    if (worksheet.Dimension != null)
                    {
                        var styleXfId = package.Workbook.Styles.NamedStyles.First(ns => (ns.Name == "Good")).StyleXfId;
                        var num3 = package.Workbook.Styles.NamedStyles.First(ns => (ns.Name == "Bad")).StyleXfId;
                        for (var i = 1; i <= worksheet.Dimension.End.Row; i++)
                        {
                            var questionText = "";
                            var answerText = "";

src/app/Tenderize/Views/Tenderize/Export.cshtml
@model Tenderize.Models.Tender
@{
    Layout = "";
}
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
@foreach (var tenderQuestion in Model.TenderQuestions.OrderBy(q => q.TenderSequence))
{
<Row>
    <Question>@Server.HtmlEncode(tenderQuestion.Question.Text.Trim())</Question>
    <Answer>@Server.HtmlEncode(tenderQuestion.HasAnswer ? tenderQuestion.Answer.Text.Trim() : "")</Answer>
</Row>
}
</Root>

src/app/Tenderize/Views/Tenderize/Import.cshtml
@using Tenderize.Models
@model Tenderize.Models.ViewModel.EditTenderViewModel

@{
    ViewBag.Title = "Sitecore© Tenderizer - Import";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script>
        $(document).ready(function() {
            var next = 1;
            $(".add-more").click(function(e) {
                e.preventDefault();
                var addto = "#field" + next;
                var addRemove = "#field" + (next);
                next = next + 1;
                var newIn = "<input autocomplete=\"off\" class=\"input form-control\" style=\"display:inline\" id=\"field" + next + "\" name=\"field" + next + "\" type=\"text\">";
                var newInput = $(newIn);
                var removeBtn = "<button id=\"remove" + (next - 1) + "\" class=\"btn btn-danger remove-me\">-</button></div><div id=\"field\">";
                var removeButton = $(removeBtn);
                $(addto).after(newInput);
                $(addRemove).after(removeButton);
                $("#field" + next).attr("data-source", $(addto).attr("data-source"));
                $("#count").val(next);

                $(".remove-me").click(function(e) {
                    e.preventDefault();
                    var fieldNum = this.id.charAt(this.id.length - 1);
                    var fieldID = "#field" + fieldNum;
                    $(this).remove();
                    $(fieldID).remove();
                });
            });
        });
    </script>
}

<h2>Import Excel (xlsx)</h2>

<div class="row">
    <h3>Tender details</h3>
    @using (Html.BeginForm("Import", "Tenderize", FormMethod.Post, new {role = "form"}))
    {
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.TextBoxFor(model => model.Name)
        </div>
        <div class="form-group">
            @Html.Label("Existing MetaTags")
            @foreach (var tag in Model.Tags)
            {
                <div class="checkbox">
                    <label>
                        <input type="checkbox" @(tag.Value.Item2 ? "checked" : "") name="metaTag_@tag.Key"> @tag.Value.Item1
                    </label>
                </div>
            }
        </div>
        <div class="form-group">
            @Html.Label("Create MetaTags")
            <div class="controls" id="profs">
                    <div id="field">
                        <input autocomplete="off" class="input form-control" style="display:inline" id="field1" name="field1" type="text" placeholder="Type something" data-items="8"/><button id="b1" class="btn add-more" type="button">+</button>
                    </div>
            </div>
        </div>

        <div class="form-group">
            @if (ViewBag.ImportFileExists && ViewBag.ExportFileExists)
            {
            <button class="btn btn-default" type="submit" name="action:Save">Save</button>
            <button class="btn btn-default" type="submit" name="action:Import">Import</button>
            }
            else
            {
            <button class="btn btn-default" type="submit" disabled title="Please upload files first" name="action:Import">Import</button>
            }
        </div>
    }
</div>

<div class="row">

    <h3>Q&A Template - Copy of file with Green/Red targeting information </h3>
    <p>Upload one copy of the tender with the question and answer sections marked out in Green and Red Styling. </p>
    <img src="../../Content/images/importexample.PNG"/>
    @if (!ViewBag.ImportFileExists)
    {
        <strong>Missing</strong>
    }
    @using (Html.BeginForm("ImportFile", "Tenderize", FormMethod.Post, new
    {
        enctype = "multipart/form-data"
    }))
    {
        <label for="fuImport">Select File</label>
        @Html.HiddenFor(model => model.Id)
        <input type="file" name="file"/>
        <input type="hidden" name="type" value="import"/>
        <input type="submit" id="btnTemplateUpload" value="Upload"/>
    }


    <h3>Export Copy - Copy of original file that answers will be exported into</h3>
    <p>Upload a copy of the original unmarked tender into which the answers will be populated on export.</p>
    <img src="../../Content/images/importexample2.PNG"/>
    @if (!ViewBag.ExportFileExists)
    {
        <strong>Missing</strong>
    }
    @using (Html.BeginForm("ImportFile", "Tenderize", FormMethod.Post, new
    {
        enctype = "multipart/form-data"
    }))
    {
        <label for="fuImport">Select File</label>
        @Html.HiddenFor(model => model.Id)
        <input type="file" name="file"/>
        <input type="hidden" name="type" value="export"/>
        <input type="submit" id="btnExportUpload" value="Upload"/>
    }




</div>

src/app/Tenderize/Views/Tenderize/Index.cshtml
@model IEnumerable<Tenderize.Models.Tender>

@{
  ViewBag.Title = "Sitecore© Tenderizer - Tenders";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
  <div class="col-md-12">
    <h1 class="well">Sitecore Tenderizer</h1>
  </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Tenders</h2>
      </div>
      <table class="table table-hover">
        <tr>
          <th>Name</th>
          <th>Questions</th>
          <th>Created</th>
          <th></th>
          <th></th>
        </tr>

        @foreach (var item in Model)
        {
          <tr>
            @Html.Partial("_Tender", item)
          </tr>
        }

      </table>
    </div>
  </div>
  <aside class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Create new</h2>
      </div>
      <div class="panel-body">
        @using (Html.BeginForm("Create", "Tenderize", FormMethod.Post, new { Class = "form-inline" }))
        {
          @Html.ValidationSummary(true)
          <span id="helpBlock" class="help-block">Please enter the name of the new tender</span>
          <div class="form-group">
            <label for="name">New tender</label>
            @Html.TextBox("name", "", new { Class = "form-control" })
          </div>
          <input type="submit" value="Create..." class="btn btn-default" />
        }
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Index tools</h2>
      </div>
      <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
          <li role="presentation"><a href=@("\"" + System.Configuration.ConfigurationManager.AppSettings["SolrUrl"] + "/update?stream.body=<delete><query>*:*</query></delete>\"")>Prime Delete</a></li>
          <li role="presentation"><a href=@("\"" + System.Configuration.ConfigurationManager.AppSettings["SolrUrl"] + "/update?stream.body=<commit/>\"")>Confirm Delete</a></li>
          <li role="presentation">@Html.ActionLink("Reindex", "Reindex")</li>
        </ul>
        <br/>
        <div class="alert alert-info">
          <div id="reindex_progress">
            @Html.Action("Progress", "Solr")
          </div>
        </div>
      </div>
    </div>
  </aside>
</div>

src/app/Tenderize/Views/Tenderize/_QuestionAnswer.cshtml
@using System.Globalization
@using Tenderize.Models
@model QuestionAnswer
@{
  ViewBag.UpVoteClass = "";
  ViewBag.UpVoteScore = 1;
  ViewBag.DownVoteClass = "";
  ViewBag.DownVoteScore = -1;

    
  if (Model.Question != null && Model.Answer != null)
  {
    var score = Model.Answer.Score;
    if (score > 0)
    {
      ViewBag.UpVoteClass = "active";
      ViewBag.DownVoteClass = "";
      ViewBag.UpVoteScore = 0;
      ViewBag.DownVoteScore = -1;
    }

    if (score < 0)
    {
      ViewBag.UpVoteClass = "";
      ViewBag.DownVoteClass = "active";
      ViewBag.UpVoteScore = 1;
      ViewBag.DownVoteScore = 0;
    }
  }
}           
@if (Model.Answer != null)
{
  <tr id="v_@(Model.Answer.Id)">
    <td id="q_@(Model.Question.Id)">
      <em>@Html.Raw(Model.Question.Text)</em>
    </td>
    <td>
      <span class="Answer" id="@(Model.Answer.Id)">@Html.Raw(Model.Answer.Text)</span>
    </td>
    <td>
      <div>
        <a class="btn btn-success" onclick="useAnswer('@Model.Answer.Id');">Use Answer</a>
      </div>
      <br/>
      <div class="panel panel-info vote">
        <div class="panel-heading">Vote <span class="badge score">@(Model.Answer.Score == 0 ? "" : Model.Answer.Score.ToString(CultureInfo.InvariantCulture))</span></div>
        <div class="panel-body">
          @using (Ajax.BeginForm("Vote", null, new AjaxOptions
          {
            UpdateTargetId = "v_" + Model.Answer.Id,
            InsertionMode = InsertionMode.ReplaceWith
          }, new
          {
            Class = "form-inline"
          }))
          {
            <input type="hidden" name="id" value='@Model.Answer.Id' />
            <input type="hidden" name="score" value='@ViewBag.UpVoteScore' />
            <button type="submit" class="btn btn-default btn-xs @ViewBag.UpVoteClass"><span class="glyphicon glyphicon-hand-up"></span></button>
          }
          @using (Ajax.BeginForm("Vote", null, new AjaxOptions
          {
              UpdateTargetId = "v_" + Model.Answer.Id,
            InsertionMode = InsertionMode.ReplaceWith
          }, new
          {
            Class = "form-inline"
          }))
          {
            <input type="hidden" name="id" value='@Model.Answer.Id' />
            <input type="hidden" name="score" value='@ViewBag.DownVoteScore' />
            <button type="submit" class="btn btn-default btn-xs @ViewBag.DownVoteClass"><span class="glyphicon glyphicon-hand-down"></span></button>
          }
        </div>
      </div>
    </td>
  </tr>
}

src/app/Tenderize/Views/Tenderize/_SearchResults.cshtml
@using Tenderize.Models
@model List<Tenderize.Models.IRelational>
           
@{
  if ((Model == null || !Model.Any()))
  {
    <tr>
      <td class="alert-warning">No results found!</td>
    </tr>
  }
  else
  {
    <tr>
      <th class="col-md-4">Questions</th>
      <th class="col-md-6">Answers</th>
      <th class="col-md-2"></th>
    </tr>
      foreach (var item in Model)
      {
          QuestionAnswer questionAnswer = null;
          if (item is Question)
          {
              var question = item as Question;
              questionAnswer = question.QuestionAnswers.Where(q => q.Answer != null).OrderByDescending(q => q.Answer.Votes.Count).FirstOrDefault();              
          }
          else if (item is Answer)
          {
              var answer = item as Answer;
              questionAnswer = answer.QuestionAnswers.FirstOrDefault();
          }
          
          if (questionAnswer != null)
          {
            @Html.Partial("_QuestionAnswer", questionAnswer)
          }
      }
  }
}

src/app/Tenderize/Views/Tenderize/_Tender.cshtml
@model Tenderize.Models.Tender
<tr> 
  <td>
    @if (Model.TenderQuestions.Count() != 0)
    {
      <a href="@Url.Action("Process", new { id = Model.FirstUnanswered.Id })">
        @Html.DisplayFor(modelItem => Model.Name)
      </a>
    }
    else
    {
      @Html.DisplayFor(modelItem => Model.Name)
    }
  </td>
  <td>
    @Html.DisplayFor(modelItem => Model.TenderQuestions.Count)
  </td>
  <td>
    @Html.DisplayFor(modelItem => Model.Date)
  </td>
  <td>
    @if (Model.TenderQuestions.Count() != 0)
    {
      @Html.ActionLink("Open", "Process", new {id = Model.FirstUnanswered.Id})
    }
    
  </td>
  <td>
    @Html.ActionLink("Export", "Export", new
    {
      id = Model.Id
    }) |
    @Html.ActionLink("Import", "Import", new
    {
      id = Model.Id
    }) |
    @Html.ActionLink("Delete", "Delete", new
    {
      id = Model.Id
    }) 
  </td>
</tr>          

src/app/Tenderize/Views/Tenderize/_TenderQuestions.cshtml
@model Tenderize.Models.Tender

<ul class="dropdown-menu list-group" role="menu">
  @foreach (var tenderQuestion in Model.TenderQuestions.OrderBy(q => q.TenderSequence))
  {
    <li role="presentation" class="list-group-item @(tenderQuestion.HasAnswer ? "" : "list-group-item-warning")">
      <a href="@Url.Action("Process", "Tenderize", new { id = tenderQuestion.Id })" title="@tenderQuestion.Question.Text">
        @tenderQuestion.TenderSequence - @tenderQuestion.Question.Text
      </a>
    </li>
  }
</ul>