src/app/Tenderize/Models/QuestionAnswer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenderize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        public QuestionAnswer()
        {
            this.TenderQuestions = new HashSet<TenderQuestion>();
        }
    
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> AnswerId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual ICollection<TenderQuestion> TenderQuestions { get; set; }
    }
}

src/app/Tenderize/Controllers/SearchController.cs
#region using

using System;
using System.Linq;
using System.Web.Mvc;
using Tenderize.Framework.Solr;
using Tenderize.Models;

#endregion

namespace Tenderize.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private static readonly TenderizeDbContext Db = new TenderizeDbContext();

        public ActionResult Index()
        {
            ViewBag.Term = "Enter a search term";
            ViewBag.HasQuery = false;
            return View();
        }

        public PartialViewResult QuestionSearch(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                ViewBag.Term = "Enter a search term";
                ViewBag.HasQuery = false;
            }
            else
            {
                var tags = from t in Db.Tags where query.Contains(t.Text) select t;
                ViewBag.MatchingTags = tags;
                var str = string.Join(", ", from t in tags select t.Text);
                ViewBag.Term = str;
                ViewBag.HasQuery = true;
                var model = SolrUtil.Find(tags);
                return PartialView("_SearchResults", model);
            }
            return PartialView("_SearchResults");
        }

        public PartialViewResult Search(string query)
        {
            if (string.IsNullOrEmpty(query))
            {
                ViewBag.Term = "Enter a question";
                ViewBag.HasQuery = false;
            }
            else
            {
                ViewBag.Term = query;
                ViewBag.HasQuery = true;
                var model = SolrUtil.Find(query);
                return PartialView("_SearchResults", model);
            }
            return PartialView("_SearchResults");
        }

        [Authorize]
        public PartialViewResult Vote(int id, long? score)
        {
            throw new NotImplementedException();
            return PartialView("_QuestionAnswer", null);

            //todo: fix voting
            //var doc = _db.Answers.FirstOrDefault(a => a.Id == id);
            //if (score.HasValue)
            //{
            //  Vote entity = doc.Votes.FirstOrDefault<Vote>(v => v.Username == User.Identity.Name);
            //  if (entity == null)
            //  {
            //    entity = new Vote
            //    {
            //      AnswerId = id,
            //      Answer = doc,
            //      Score = score.Value,
            //      Username = User.Identity.Name
            //    };
            //    _db.Votes.Add(entity);
            //  }
            //  else if (score == 0L)
            //    _db.Votes.Remove(entity);
            //  else
            //  {
            //    entity.Score = score.Value;
            //    _db.Entry(entity).CurrentValues.SetValues(entity);
            //  }
            //  _db.SaveChanges();
            //  var instance = SolrUtil.GetSolrInstance<IRelational>();
            //  instance.AddWithBoost(doc, doc.Score*10.0);
            //  var question = doc.Questions.FirstOrDefault();
            //  if (question != null)
            //    instance.AddWithBoost(question, doc.Score*10.0);
            //  instance.Commit();
            //}
            //return PartialView("_QuestionAnswer", doc.Questions.FirstOrDefault<Question>());
        }
    }
}

src/app/Tenderize/Views/Search/Index.cshtml
@using System.Collections.Generic
@using Tenderize.Models

@{
  ViewBag.Title = "Sitecore© Tenderizer - Search";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Search</h1>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Search for Question
      </div>
      <div class="panel-body">
        @using (Ajax.BeginForm("QuestionSearch", "Search", new AjaxOptions
        {
          HttpMethod = "GET",
          UpdateTargetId = "searchResults",
          LoadingElementId = "loading",
          OnBegin = "$('#searchResults').html('')"
        }))
        {
          <div class="form-group">
            <textarea id="textAdd" rows="5" name="query" class="form-control"></textarea>
          </div>
          <input type="submit" value="Search" />
        }
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Search for specific term
      </div>
      <div class="panel-body">

        @using (Ajax.BeginForm("Search", "Search", new AjaxOptions
        {
          HttpMethod = "GET",
          UpdateTargetId = "searchResults",
          LoadingElementId = "loading",
          OnBegin = "$('#searchResults').html('')"
        }))
        {
          <div class="form-group">
            <input type="text" name="query" id="searchText" class="form-control" />
          </div>
          <input type="submit" value="Search" />
        }
      </div>
    </div>
  </div>
</div>
<div id="loading" style="display: none;" class="row">
  <div class="col-md-12">
    <div class="alert alert-info" role="alert">Searching...</div>
  </div>
</div>

<div class="row">
  <div class="col-md-12" id="searchResults">
    @Html.Partial("_SearchResults", ViewBag.Results as List<Question>)

  </div>
</div>

src/app/Tenderize/Views/Search/_QuestionAnswer.cshtml
@using System.Web.Configuration
@using Tenderize.Models
@model Tenderize.Models.IRelational
@{
    Question question;
    Answer answer;
    if (Model is Question)
    {
        question = (Question) Model;
        //answer = question.QuestionAnswers.FirstOrDefault()
        answer = (from q in question.QuestionAnswers
            where q.Answer != null
            orderby q.Answer.Tags.Sum(t => t.Popularity) descending
            select q.Answer).FirstOrDefault();
    }
    else
    {
        answer = (Answer) Model;
        
        //todo: order by created date - need to add field to db
        question = (from a in answer.QuestionAnswers
            select a.Question).FirstOrDefault();

    }
  //var vote = Model..First().Votes.FirstOrDefault(v => v.Username == User.Identity.Name);
  //if (vote != null)
  //{
  //  if (vote.Score > 0)
  //  {
  //    ViewBag.UpVoteClass = "upVoted";
  //    ViewBag.UpVoteScore = 0;
  //    ViewBag.DownVoteClass = "downVote";
  //    ViewBag.DownVoteScore = -1;
  //  }
  //  else
  //  {
  //    ViewBag.UpVoteClass = "upVote";
  //    ViewBag.UpVoteScore = 1;
  //    ViewBag.DownVoteClass = "downVoted";
  //    ViewBag.DownVoteScore = 0;
  //  }
  //}
  //else
  //{
  //  ViewBag.UpVoteClass = "upVote";
  //  ViewBag.UpVoteScore = 1;
  //  ViewBag.DownVoteClass = "downVote";
  //  ViewBag.DownVoteScore = -1;
  //}
}

@if (answer != null) {
    <tr id="v_@(answer.Id)">
        @if (question != null)
        {
            <td id="q_@(question.Id)">
                @Html.Raw(question.Text)
            </td>
        }
        else
        {
            <td></td>
        }
        <td class="Answer" id="@(answer.Id)">
            @Html.Raw(answer.Text)
        </td>
    </tr>
}

src/app/Tenderize/Views/Search/_SearchResults.cshtml
@using System.Linq
@model List<Tenderize.Models.IRelational>
           
@{
  string term = ViewBag.Term;
}

<div class="panel panel-primary">
  <div class="panel-heading">
    Search Results
  </div>
    @{
      if ((Model == null || !Model.Any()))
      {
        <div class="panel-body">
          No results found!
        </div>      
      }
      else
      {
        <div class="panel-body">
          Searched for: @ViewBag.Term
        </div>
        <table class="table table-hover">
          <tr>
            <th class="col-md-4">Questions</th>
            <th class="col-md-6">Answers</th>
          </tr>
          @{
            foreach (var question in Model)
            {
              @Html.Partial("_QuestionAnswer", question)
            }
          }

        </table>
      }
    }
  </div>